flaskr/models/comment_model.py
from .db import db


class CommentModel(db.Model):
    __tablename__ = 'comment'
    id = db.Column('id', db.Integer, primary_key=True, autoincrement=True)
    user_id = db.Column('user_id', db.Integer, db.ForeignKey('user.id'))
    post_id = db.Column('post_id', db.Integer, db.ForeignKey('post.id'))
    text_comment = db.Column('text_comment', db.Text, nullable=False)
    created = db.Column('created', db.DateTime, nullable=False)

flaskr/models/db.py
from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()

flaskr/models/post_model.py
from .db import db


class PostModel(db.Model):
    __tablename__ = 'post'
    id = db.Column('id', db.Integer, primary_key=True, autoincrement=True)
    author_id = db.Column('author_id', db.Integer, db.ForeignKey('user.id'))
    created = db.Column('created', db.DateTime, nullable=False)
    title = db.Column('title', db.Text, nullable=False)
    body = db.Column('body', db.Text, nullable=False)
    comments = db.relationship('CommentModel', backref='post')

flaskr/models/user_model.py
from .db import db


class UserModel(db.Model):
    __tablename__ = 'user'
    id = db.Column('id', db.Integer, primary_key=True, autoincrement=True)
    username = db.Column('username', db.String, nullable=False, unique=True)
    password = db.Column('password', db.String, nullable=False, unique=True)
    posts = db.relationship('PostModel', backref='user')
    comments = db.relationship('CommentModel', backref='user')

flaskr/__init__.py
from flask import Flask
from flask_migrate import Migrate
from .models.db import db
from .config import Config, DevConfig, HerokuConfig
import os


def create_app(test_config=None):
    # create and configure the app
    app = Flask(__name__, instance_relative_config=True)

    if test_config is None:
        # load the instance config, if it exists
        app.config.from_object(Config)
        env = os.environ.get('FLASK_CONFIG', "")
        if env == "Heroku":
            app.config.from_object(HerokuConfig)
        elif env == "Dev":
            app.config.from_object(DevConfig)
        else:
            pass
    else:
        # load the test config if passed in
        app.config.from_mapping(test_config)

    from . import auth
    app.register_blueprint(auth.bp)

    from . import blog
    app.register_blueprint(blog.bp)
    app.add_url_rule('/', endpoint='index')

    from .models import comment_model, post_model, user_model

    db.init_app(app)
    migrate = Migrate(app, db)

    return app

flaskr/auth.py
import functools

from flask import (
    Blueprint, flash, g, redirect, render_template, request, session, url_for
)
from werkzeug.security import check_password_hash
from .controllers.user_controller import UserController

bp = Blueprint('auth', __name__, url_prefix='/auth')


@bp.route('/register', methods=('GET', 'POST'))
def register():
    if request.method == 'POST':
        username = request.form['username']
        password = request.form['password']
        error = None

        if not username:
            error = 'Username is required.'
        elif not password:
            error = 'Password is required.'
        elif UserController.search_user(username) is not None:
            error = 'User {} is already registered.'.format(username)

        if error is None:
            UserController.create_user(username, password)
            return redirect(url_for('auth.login'))

        flash(error)

    return render_template('auth/register.html')


@bp.route('/login', methods=('GET', 'POST'))
def login():
    if request.method == 'POST':
        username = request.form['username']
        password = request.form['password']
        error = None

        user = UserController.search_user(username)
        if user is None:
            error = 'Incorrect username.'
        elif not check_password_hash(user.password, password):
            error = 'Incorrect password.'

        if error is None:
            session.clear()
            session['user_id'] = user.id
            session['username'] = user.username
            return redirect(url_for('index'))

        flash(error)

    return render_template('auth/login.html')


@bp.before_app_request
def load_logged_in_user():
    user_id = session.get('user_id')

    if user_id is None:
        g.user = None
    else:
        g.user = UserController.get_users(user_id)


@bp.route('/logout')
def logout():
    session.clear()
    return redirect(url_for('index'))


def login_required(view):
    @functools.wraps(view)
    def wrapped_view(**kwargs):
        if g.user is None:
            return redirect(url_for('auth.login'))
        return view(**kwargs)
    return wrapped_view

flaskr/controllers/comment_controller.py
from ..models.comment_model import CommentModel
from ..models.db import db
from datetime import datetime


class CommentController:

    @staticmethod
    def get_comments(comment_id=None):
        if comment_id is not None:
            return CommentModel.query.all()
        else:
            return CommentModel.query.filter(
                CommentModel.id == comment_id
            ).first()

    @staticmethod
    def get_comments_post(post_id):
        return CommentModel.query.filter(CommentModel.post_id == post_id).all()

    @staticmethod
    def create_comment(comment, author_id, post_id):
        new_comment = CommentModel(text_comment=comment, post_id=post_id,
                                   user_id=author_id, created=datetime.now())
        if new_comment is not None:
            db.session.add(new_comment)
            db.session.commit()
            return True
        else:
            return False

    @staticmethod
    def delete_comment(post_id):
        post = CommentModel.query.filter(CommentModel.id == post_id).first()
        if post is not None:
            db.session.delete(post)
            db.session.commit()
            return True
        else:
            return False

flaskr/controllers/post_controller.py
from ..models.post_model import PostModel
from ..models.db import db
from datetime import datetime


class PostController:

    @staticmethod
    def get_posts(post_id=None):
        if post_id is None:
            return PostModel.query.all()
        else:
            return PostModel.query.filter(PostModel.id == post_id).first()

    @staticmethod
    def create_post(title, body, author_id):
        new_post = PostModel(title=title, body=body,
                             author_id=author_id, created=datetime.now())
        db.session.add(new_post)
        db.session.commit()

    @staticmethod
    def delete_post(post_id):
        post = PostModel.query.filter(PostModel.id == post_id).first()
        if post is not None:
            db.session.delete(post)
            db.session.commit()
            return True
        else:
            return False

    @staticmethod
    def update_post(post_id, title, body):
        post = PostModel.query.filter(PostModel.id == post_id).first()
        if post is not None:
            post.title = title
            post.body = body
            db.session.add(post)
            db.session.commit()
            return True
        else:
            return False

    @staticmethod
    def search_posts(search_term):
        posts = PostModel.query.filter(
            PostModel.title.like('%' + search_term + '%')
        ).all()
        return posts

flaskr/controllers/user_controller.py
from ..models.user_model import UserModel
from ..models.db import db
from werkzeug.security import generate_password_hash


class UserController:

    @staticmethod
    def get_users(user_id=None):
        if user_id is not None:
            return UserModel.query.all()
        else:
            return UserModel.query.filter(UserModel.id == user_id).first()

    @staticmethod
    def create_user(username, password):
        new_user = UserModel(username=username,
                             password=generate_password_hash(password))
        db.session.add(new_user)
        db.session.commit()

    @staticmethod
    def delete_user(user_id):
        user = UserModel.query.filter(UserModel.id == user_id).first()
        db.session.delete(user)
        db.session.commit()

    @staticmethod
    def search_user(username):
        user = UserModel.query.filter(UserModel.username == username).first()
        return user

flaskr/templates/base.html
<!doctype html>
<title>{% block title %}{% endblock %} - Flaskr</title>

<link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
<link rel="stylesheet" href="{{ url_for('static', filename='bootstrap/css/bootstrap.min.css') }}">

<script src="{{ url_for('static', filename='jquery-3.3.1.min.js') }}"></script>
<script src="{{ url_for('static', filename='popper.min.js') }}"></script>
<script src="{{ url_for('static', filename='bootstrap/js/bootstrap.min.js') }}"></script>

<script>
    $(document).ready(function() {
       $('#search-button').click(function(){
          var query = $('#search').val();
          window.location = "/search?search=" + query;
       });
    });
 </script>

<div class="container">
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{{ url_for('blog.index') }}">
      <h2 class="my-1">My Blog</h2>
    </a>
    <div class="form-group row ml-3 my-2">
      <input name="search" id="search" class="form-control col-8" type="search" placeholder="Search" aria-label="Search">
      <button id="search-button" class="btn btn-outline-success col-3 mx-1" type="submit">Search</button>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="navbar-nav ml-auto">  
        {% if g.user %}
          <li class="nav-link">
              <a class="btn btn-danger" href="{{ url_for('auth.logout') }}">
                Logout
              </a>
          </li>
        {% else %}
          <li class="nav-link"><a class="btn btn-primary" href="{{ url_for('auth.register') }}">Register</a></li>
          <li class="nav-link"><a class="btn btn-success" href="{{ url_for('auth.login') }}">Log In</a></li>
        {% endif %}
      </ul>
    </div>
  </nav>
  <div class="container">
    <section class="content">
      <header>
        {% block header %}{% endblock %}
      </header>
      {% for message in get_flashed_messages() %}
        <div class="flash">{{ message }}</div>
      {% endfor %}
      {% block content %}{% endblock %}
    </section>
  </div>
</div>

flaskr/templates/blog/create.html
{% extends 'base.html' %}

{% block header %}
  <h1>{% block title %}New Post{% endblock %}</h1>
{% endblock %}

{% block content %}
  <div class="form-group">
    <form method="post">
      <label for="title">Title</label>
      <input class="form-control" name="title" id="title" value="{{ request.form['title'] }}" required>
      <label for="body">Body</label>
      <textarea class="form-control" name="body" id="body">{{ request.form['body'] }}</textarea>
      <div class="row">
        <input class="btn btn-success ml-auto my-1 mx-3" type="submit" value="Save">
      </div>
    </form>
  </div>
{% endblock %}

flaskr/templates/blog/details.html
{% extends 'base.html' %}

{% block header %}
  <h1>{% block title %}{{ post['title'] }}{% endblock %}</h1>
{% endblock %}

{% block content %}
  <div class="container">
    <div class="form-group">
      <textarea name="body" id="body" class="form-control" readonly>
        {{ post['body'] }}
      </textarea>
    </div>
  </div>
  <form class="form-group" action=" {{ url_for('blog.comment', post_id=post['id']) }} " method="post">
    <label for="comment">Comment: </label>
    <input type="text" class="form-control" name="comment" placeholder="Comment..." />
    <button type="submit" class="btn btn-primary">Submit</button>
  </form>
  <div class="container">
    {% for comment in comments %}
      <div class="form-group">
        <label>{{ comment.user['username'] }} escreveu: </label>
        <textarea class="form-control" disabled="true" readonly>{{ comment['text_comment'] }}</textarea>
      </div>
    {% endfor %}
  </div>
  <a class="btn" href={{ url_for('blog.index') }}>Voltar</a>
{% endblock %}

flaskr/templates/blog/index.html
{% extends 'base.html' %}

{% block title %}
Index
{% endblock %}

{% block header %}
  {% if g.user %}
    <div class="container">
      <div class="row">
        <a class="btn btn-success my-2 col-2" href="{{ url_for('blog.create') }}">New Post</a>
        {% if g.user %}
          <h6 class="ml-auto my-3">Bem vindo, {{ session['username'] }}.</h6>
        {% endif %}
      </div>
    </div>
  {% endif %}
{% endblock %}

{% block content %}
  {% for post in posts %}
    <div class="card my-1">
      <div class="card-body">
        <h2 class="card-title">
          <a href="{{ url_for('blog.details', post_id=post['id']) }}">
              {{ post['title'] }}
          </a>
        </h2>
        <p class="card-text my-2">{{ post['body'] }}</p>
        <p class="card-text">
          <small class="text-muted">
            by {{ post.user['username'] }} on {{ post['created'].strftime('%Y-%m-%d') }}
          </small>
        </p>
        <div class="row">
          {% if g.user['id'] == post['author_id'] %}
            <a class="btn btn-primary ml-auto" href="{{ url_for('blog.update', post_id=post['id']) }}">Edit</a>
          {% endif %}
        </div>
      </div>
    </div>
    {% if not loop.last %}
      <hr>
    {% endif %}
  {% endfor %}
{% endblock %}

flaskr/templates/blog/search.html
{% extends 'base.html' %}

{% block title %}
Search Results
{% endblock %}

{% block header %}
  <h1>Search results</h1>
{% endblock %}

{% block content %}
  {% for post in posts %}
    <article>
      <header>
        <div>
          <h1>
              <a href="{{ url_for('blog.details', id=post['id']) }}">
                  {{ post['title'] }}
              </a>
          </h1>
          <div>by {{ post['username'] }} on {{ post['created'].strftime('%Y-%m-%d') }}</div>
        </div>
        {% if g.user['id'] == post['author_id'] %}
          <a href="{{ url_for('blog.update', id=post['id']) }}">Edit</a>
        {% endif %}
      </header>
      <p>{{ post['body'] }}</p>
    </article>
    {% if not loop.last %}
      <hr>
    {% endif %}
  {% endfor %}
{% endblock %}

flaskr/templates/blog/update.html
{% extends 'base.html' %}

{% block header %}
  
{% endblock %}

{% block content %}
  <form class="form-group" method="post">
    <label for="title">Title</label>
    <input class="form-control" name="title" id="title"
      value="{{ request.form['title'] or post['title'] }}" required>
    <label for="body">Body</label>
    <textarea class="form-control" name="body" id="body">{{ request.form['body'] or post['body'] }}</textarea>
    <div class="row">
      <div class="ml-auto mx-3 my-2"> 
        <input class="btn btn-danger" type="submit" value="Delete" onclick="return confirm('Are you sure?');">
        <input class="btn btn-success" type="submit" value="Save">
      </div>
    </div>
  </form>
  <hr>
{% endblock %}